package com.prowidesoftware.swift.model.mx.adapters;

import static org.assertj.core.api.Assertions.assertThat;

import com.prowidesoftware.swift.model.mx.AbstractMX;
import com.prowidesoftware.swift.model.mx.MxSese02500109;
import org.junit.jupiter.api.DisplayNameGeneration;
import org.junit.jupiter.api.DisplayNameGenerator;
import org.junit.jupiter.api.Test;

@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
class DateTimeJsonAdapterBackwardCompatibilityTest {
    private static final String XML_MX = "<?xml version=\"1.0\"?>\n"
            + "    <RequestPayload xmlns=\"urn:iso:std:iso:20022:tech:xsd:head.003.001.01\">\n"
            + "      <AppHdr xmlns=\"urn:iso:std:iso:20022:tech:xsd:head.001.001.01\">\n"
            + "        <Fr>\n"
            + "          <FIId>\n"
            + "            <FinInstnId>\n"
            + "              <BICFI>IJKLMNOPXXX</BICFI>\n"
            + "              <Othr>\n"
            + "                <Id>ABCDEFGHXXX</Id>\n"
            + "              </Othr>\n"
            + "            </FinInstnId>\n"
            + "          </FIId>\n"
            + "        </Fr>\n"
            + "        <To>\n"
            + "          <FIId>\n"
            + "            <FinInstnId>\n"
            + "              <BICFI>ABCDEFGHXXX</BICFI>\n"
            + "              <Othr>\n"
            + "                <Id>ABCDEFGHXXX</Id>\n"
            + "              </Othr>\n"
            + "            </FinInstnId>\n"
            + "          </FIId>\n"
            + "        </To>\n"
            + "        <BizMsgIdr>1423905641002</BizMsgIdr>\n"
            + "        <MsgDefIdr>sese.025.001.09</MsgDefIdr>\n"
            + "        <CreDt>2024-07-17T05:27:51Z</CreDt>\n"
            + "        <CpyDplct>COPY</CpyDplct>\n"
            + "        <PssblDplct>true</PssblDplct>\n"
            + "        <Prty>2024071700000208</Prty>\n"
            + "      </AppHdr>\n"
            + "      <Document xmlns=\"urn:iso:std:iso:20022:tech:xsd:sese.025.001.09\">\n"
            + "        <SctiesSttlmTxConf>\n"
            + "          <TxIdDtls>\n"
            + "            <AcctOwnrTxId>FOO</AcctOwnrTxId>\n"
            + "            <MktInfrstrctrTxId>BAR</MktInfrstrctrTxId>\n"
            + "            <PrcrTxId>TOTO</PrcrTxId>\n"
            + "            <SctiesMvmntTp>RECE</SctiesMvmntTp>\n"
            + "            <Pmt>APMT</Pmt>\n"
            + "            <CmonId>TITI</CmonId>\n"
            + "          </TxIdDtls>\n"
            + "          <TradDtls>\n"
            + "            <PlcOfTrad>\n"
            + "              <MktTpAndId>\n"
            + "                <Tp>\n"
            + "                  <Cd>EXCH</Cd>\n"
            + "                </Tp>\n"
            + "              </MktTpAndId>\n"
            + "            </PlcOfTrad>\n"
            + "            <PlcOfClr>\n"
            + "              <Id>QRSTUVWYXXX</Id>\n"
            + "            </PlcOfClr>\n"
            + "            <TradDt>\n"
            + "              <Dt>\n"
            + "                <Dt>2024-07-16</Dt>\n"
            + "              </Dt>\n"
            + "            </TradDt>\n"
            + "            <SttlmDt>\n"
            + "              <Dt>\n"
            + "                <Dt>2024-07-17</Dt>\n"
            + "              </Dt>\n"
            + "            </SttlmDt>\n"
            + "            <FctvSttlmDt>\n"
            + "              <Dt>\n"
            + "                <DtTm>2024-07-17T07:26:04.207459</DtTm>\n"
            + "              </Dt>\n"
            + "            </FctvSttlmDt>\n"
            + "          </TradDtls>\n"
            + "          <FinInstrmId>\n"
            + "            <ISIN>NL0000009165</ISIN>\n"
            + "          </FinInstrmId>\n"
            + "          <QtyAndAcctDtls>\n"
            + "            <SttldQty>\n"
            + "              <Qty>\n"
            + "                <Unit>0</Unit>\n"
            + "              </Qty>\n"
            + "            </SttldQty>\n"
            + "            <SfkpgAcct>\n"
            + "              <Id>NECISOGEFRPPAGN000L10</Id>\n"
            + "            </SfkpgAcct>\n"
            + "            <CshAcct>\n"
            + "              <Prtry>CFREURSOGEFRPPTIT-DCA-SGSS</Prtry>\n"
            + "            </CshAcct>\n"
            + "          </QtyAndAcctDtls>\n"
            + "          <SttlmParams>\n"
            + "            <SctiesTxTp>\n"
            + "              <Cd>NETT</Cd>\n"
            + "            </SctiesTxTp>\n"
            + "            <PrtlSttlmInd>PARQ</PrtlSttlmInd>\n"
            + "            <CshSubBalTp>\n"
            + "              <Id>DLVR</Id>\n"
            + "              <Issr>T2S</Issr>\n"
            + "              <SchmeNm>RT</SchmeNm>\n"
            + "            </CshSubBalTp>\n"
            + "          </SttlmParams>\n"
            + "          <DlvrgSttlmPties>\n"
            + "            <Dpstry>\n"
            + "              <Id>\n"
            + "                <AnyBIC>ABCDEFGHXXX</AnyBIC>\n"
            + "              </Id>\n"
            + "              <PrcgId>2407162881091741</PrcgId>\n"
            + "            </Dpstry>\n"
            + "            <Pty1>\n"
            + "              <Id>\n"
            + "                <AnyBIC>QRSTUVWYXXX</AnyBIC>\n"
            + "              </Id>\n"
            + "              <SfkpgAcct>\n"
            + "                <Id>MOTICCEGITRRXXX9100000</Id>\n"
            + "              </SfkpgAcct>\n"
            + "              <PrcgId>1VUVZK</PrcgId>\n"
            + "            </Pty1>\n"
            + "          </DlvrgSttlmPties>\n"
            + "          <RcvgSttlmPties>\n"
            + "            <Dpstry>\n"
            + "              <Id>\n"
            + "                <AnyBIC>HGFEDCBAXXX</AnyBIC>\n"
            + "              </Id>\n"
            + "            </Dpstry>\n"
            + "            <Pty1>\n"
            + "              <Id>\n"
            + "                <AnyBIC>SOGEFRPPAGN</AnyBIC>\n"
            + "              </Id>\n"
            + "              <SfkpgAcct>\n"
            + "                <Id>NECISOGEFRPPAGN000L10</Id>\n"
            + "              </SfkpgAcct>\n"
            + "              <PrcgId>FOO</PrcgId>\n"
            + "            </Pty1>\n"
            + "          </RcvgSttlmPties>\n"
            + "          <SttldAmt>\n"
            + "            <Amt Ccy=\"EUR\">1</Amt>\n"
            + "            <CdtDbtInd>DBIT</CdtDbtInd>\n"
            + "          </SttldAmt>\n"
            + "          <SplmtryData>\n"
            + "            <PlcAndNm>/Document/SctiesSttlmTxConf/TxIdDtls</PlcAndNm>\n"
            + "            <Envlp>\n"
            + "              <Document xmlns=\"urn:eurosystem:xsd:DRAFT2supl.021.001.01\">\n"
            + "                <SctiesSttlmSD1>\n"
            + "                  <RltdTxId>42</RltdTxId>\n"
            + "                </SctiesSttlmSD1>\n"
            + "              </Document>\n"
            + "            </Envlp>\n"
            + "          </SplmtryData>\n"
            + "        </SctiesSttlmTxConf>\n"
            + "      </Document>\n"
            + "    </RequestPayload>";

    private static final String JSON_MX_V9 = "{\n" + "      \"sctiesSttlmTxConf\": {\n"
            + "        \"txIdDtls\": {\n"
            + "          \"acctOwnrTxId\": \"FOO\",\n"
            + "          \"mktInfrstrctrTxId\": \"BAR\",\n"
            + "          \"prcrTxId\": \"TOTO\",\n"
            + "          \"sctiesMvmntTp\": \"RECE\",\n"
            + "          \"pmt\": \"APMT\",\n"
            + "          \"cmonId\": \"TITI\"\n"
            + "        },\n"
            + "        \"tradDtls\": {\n"
            + "          \"plcOfTrad\": {\n"
            + "            \"mktTpAndId\": {\n"
            + "              \"tp\": {\n"
            + "                \"cd\": \"EXCH\"\n"
            + "              }\n"
            + "            }\n"
            + "          },\n"
            + "          \"plcOfClr\": {\n"
            + "            \"id\": \"QRSTUVWYXXX\"\n"
            + "          },\n"
            + "          \"tradDt\": {\n"
            + "            \"dt\": {\n"
            + "              \"dt\": {\n"
            + "                \"year\": 2024,\n"
            + "                \"month\": 7,\n"
            + "                \"day\": 16,\n"
            + "                \"timezone\": -2147483648,\n"
            + "                \"hour\": -2147483648,\n"
            + "                \"minute\": -2147483648,\n"
            + "                \"second\": -2147483648\n"
            + "              }\n"
            + "            }\n"
            + "          },\n"
            + "          \"sttlmDt\": {\n"
            + "            \"dt\": {\n"
            + "              \"dt\": {\n"
            + "                \"year\": 2024,\n"
            + "                \"month\": 7,\n"
            + "                \"day\": 17,\n"
            + "                \"timezone\": -2147483648,\n"
            + "                \"hour\": -2147483648,\n"
            + "                \"minute\": -2147483648,\n"
            + "                \"second\": -2147483648\n"
            + "              }\n"
            + "            }\n"
            + "          },\n"
            + "          \"fctvSttlmDt\": {\n"
            + "            \"dt\": {\n"
            + "              \"dtTm\": {\n"
            + "                \"year\": 2024,\n"
            + "                \"month\": 7,\n"
            + "                \"day\": 17,\n"
            + "                \"timezone\": -2147483648,\n"
            + "                \"hour\": 7,\n"
            + "                \"minute\": 26,\n"
            + "                \"second\": 4,\n"
            + "                \"fractionalSecond\": 0.207459\n"
            + "              }\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"finInstrmId\": {\n"
            + "          \"isin\": \"NL0000009165\"\n"
            + "        },\n"
            + "        \"qtyAndAcctDtls\": {\n"
            + "          \"sttldQty\": {\n"
            + "            \"qty\": {\n"
            + "              \"unit\": 0\n"
            + "            }\n"
            + "          },\n"
            + "          \"sfkpgAcct\": {\n"
            + "            \"id\": \"NECISOGEFRPPAGN000L10\"\n"
            + "          },\n"
            + "          \"cshAcct\": {\n"
            + "            \"prtry\": \"CFREURSOGEFRPPTIT-DCA-SGSS\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"sttlmParams\": {\n"
            + "          \"sctiesTxTp\": {\n"
            + "            \"cd\": \"NETT\"\n"
            + "          },\n"
            + "          \"prtlSttlmInd\": \"PARQ\",\n"
            + "          \"cshSubBalTp\": {\n"
            + "            \"id\": \"DLVR\",\n"
            + "            \"issr\": \"T2S\",\n"
            + "            \"schmeNm\": \"RT\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"dlvrgSttlmPties\": {\n"
            + "          \"dpstry\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"ABCDEFGHXXX\"\n"
            + "            },\n"
            + "            \"prcgId\": \"2407162881091741\"\n"
            + "          },\n"
            + "          \"pty1\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"QRSTUVWYXXX\"\n"
            + "            },\n"
            + "            \"sfkpgAcct\": {\n"
            + "              \"id\": \"MOTICCEGITRRXXX9100000\"\n"
            + "            },\n"
            + "            \"prcgId\": \"1VUVZK\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"rcvgSttlmPties\": {\n"
            + "          \"dpstry\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"HGFEDCBAXXX\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"pty1\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"SOGEFRPPAGN\"\n"
            + "            },\n"
            + "            \"sfkpgAcct\": {\n"
            + "              \"id\": \"NECISOGEFRPPAGN000L10\"\n"
            + "            },\n"
            + "            \"prcgId\": \"FOO\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"sttldAmt\": {\n"
            + "          \"amt\": {\n"
            + "            \"value\": 1,\n"
            + "            \"ccy\": \"EUR\"\n"
            + "          },\n"
            + "          \"cdtDbtInd\": \"DBIT\"\n"
            + "        },\n"
            + "        \"splmtryData\": [\n"
            + "          {\n"
            + "            \"plcAndNm\": \"/Document/SctiesSttlmTxConf/TxIdDtls\",\n"
            + "            \"envlp\": {}\n"
            + "          }\n"
            + "        ]\n"
            + "      },\n"
            + "      \"appHdr\": {\n"
            + "        \"fr\": {\n"
            + "          \"fiId\": {\n"
            + "            \"finInstnId\": {\n"
            + "              \"bicfi\": \"IJKLMNOPXXX\",\n"
            + "              \"othr\": {\n"
            + "                \"id\": \"ABCDEFGHXXX\"\n"
            + "              }\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"to\": {\n"
            + "          \"fiId\": {\n"
            + "            \"finInstnId\": {\n"
            + "              \"bicfi\": \"ABCDEFGHXXX\",\n"
            + "              \"othr\": {\n"
            + "                \"id\": \"ABCDEFGHXXX\"\n"
            + "              }\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"bizMsgIdr\": \"1423905641002\",\n"
            + "        \"msgDefIdr\": \"sese.025.001.09\",\n"
            + "        \"creDt\": {\n"
            + "          \"year\": 2024,\n"
            + "          \"month\": 7,\n"
            + "          \"day\": 17,\n"
            + "          \"timezone\": 0,\n"
            + "          \"hour\": 5,\n"
            + "          \"minute\": 27,\n"
            + "          \"second\": 51\n"
            + "        },\n"
            + "        \"cpyDplct\": \"COPY\",\n"
            + "        \"pssblDplct\": true,\n"
            + "        \"prty\": \"2024071700000208\",\n"
            + "        \"namespace\": \"urn:iso:std:iso:20022:tech:xsd:head.001.001.01\"\n"
            + "      },\n"
            + "      \"type\": \"MX\",\n"
            + "      \"@xmlns\": \"urn:iso:std:iso:20022:tech:xsd:sese.025.001.09\",\n"
            + "      \"identifier\": \"sese.025.001.09\"\n"
            + "    }";

    private static final String JSON_MX_V10 = "{\n" + "      \"sctiesSttlmTxConf\": {\n"
            + "        \"txIdDtls\": {\n"
            + "          \"acctOwnrTxId\": \"FOO\",\n"
            + "          \"mktInfrstrctrTxId\": \"BAR\",\n"
            + "          \"prcrTxId\": \"TOTO\",\n"
            + "          \"sctiesMvmntTp\": \"RECE\",\n"
            + "          \"pmt\": \"APMT\",\n"
            + "          \"cmonId\": \"TITI\"\n"
            + "        },\n"
            + "        \"tradDtls\": {\n"
            + "          \"plcOfTrad\": {\n"
            + "            \"mktTpAndId\": {\n"
            + "              \"tp\": {\n"
            + "                \"cd\": \"EXCH\"\n"
            + "              }\n"
            + "            }\n"
            + "          },\n"
            + "          \"plcOfClr\": {\n"
            + "            \"id\": \"QRSTUVWYXXX\"\n"
            + "          },\n"
            + "          \"tradDt\": {\n"
            + "            \"dt\": {\n"
            + "              \"dt\": {\n"
            + "                \"year\": 2024,\n"
            + "                \"month\": 7,\n"
            + "                \"day\": 16\n"
            + "              }\n"
            + "            }\n"
            + "          },\n"
            + "          \"sttlmDt\": {\n"
            + "            \"dt\": {\n"
            + "              \"dt\": {\n"
            + "                \"year\": 2024,\n"
            + "                \"month\": 7,\n"
            + "                \"day\": 17\n"
            + "              }\n"
            + "            }\n"
            + "          },\n"
            + "          \"fctvSttlmDt\": {\n"
            + "            \"dt\": {\n"
            + "              \"dtTm\": {\n"
            + "                \"dateTime\": {\n"
            + "                  \"date\": {\n"
            + "                    \"year\": 2024,\n"
            + "                    \"month\": 7,\n"
            + "                    \"day\": 17\n"
            + "                  },\n"
            + "                  \"time\": {\n"
            + "                    \"hour\": 7,\n"
            + "                    \"minute\": 26,\n"
            + "                    \"second\": 4,\n"
            + "                    \"nano\": 207459000\n"
            + "                  }\n"
            + "                },\n"
            + "                \"offset\": {\n"
            + "                  \"totalSeconds\": 7200\n"
            + "                }\n"
            + "              }\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"finInstrmId\": {\n"
            + "          \"isin\": \"NL0000009165\"\n"
            + "        },\n"
            + "        \"qtyAndAcctDtls\": {\n"
            + "          \"sttldQty\": {\n"
            + "            \"qty\": {\n"
            + "              \"unit\": 0\n"
            + "            }\n"
            + "          },\n"
            + "          \"sfkpgAcct\": {\n"
            + "            \"id\": \"NECISOGEFRPPAGN000L10\"\n"
            + "          },\n"
            + "          \"cshAcct\": {\n"
            + "            \"prtry\": \"CFREURSOGEFRPPTIT-DCA-SGSS\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"sttlmParams\": {\n"
            + "          \"sctiesTxTp\": {\n"
            + "            \"cd\": \"NETT\"\n"
            + "          },\n"
            + "          \"prtlSttlmInd\": \"PARQ\",\n"
            + "          \"cshSubBalTp\": {\n"
            + "            \"id\": \"DLVR\",\n"
            + "            \"issr\": \"T2S\",\n"
            + "            \"schmeNm\": \"RT\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"dlvrgSttlmPties\": {\n"
            + "          \"dpstry\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"ABCDEFGHXXX\"\n"
            + "            },\n"
            + "            \"prcgId\": \"2407162881091741\"\n"
            + "          },\n"
            + "          \"pty1\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"QRSTUVWYXXX\"\n"
            + "            },\n"
            + "            \"sfkpgAcct\": {\n"
            + "              \"id\": \"MOTICCEGITRRXXX9100000\"\n"
            + "            },\n"
            + "            \"prcgId\": \"1VUVZK\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"rcvgSttlmPties\": {\n"
            + "          \"dpstry\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"HGFEDCBAXXX\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"pty1\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"SOGEFRPPAGN\"\n"
            + "            },\n"
            + "            \"sfkpgAcct\": {\n"
            + "              \"id\": \"NECISOGEFRPPAGN000L10\"\n"
            + "            },\n"
            + "            \"prcgId\": \"FOO\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"sttldAmt\": {\n"
            + "          \"amt\": {\n"
            + "            \"value\": 1,\n"
            + "            \"ccy\": \"EUR\"\n"
            + "          },\n"
            + "          \"cdtDbtInd\": \"DBIT\"\n"
            + "        },\n"
            + "        \"splmtryData\": [\n"
            + "          {\n"
            + "            \"plcAndNm\": \"/Document/SctiesSttlmTxConf/TxIdDtls\",\n"
            + "            \"envlp\": {}\n"
            + "          }\n"
            + "        ]\n"
            + "      },\n"
            + "      \"appHdr\": {\n"
            + "        \"fr\": {\n"
            + "          \"fiId\": {\n"
            + "            \"finInstnId\": {\n"
            + "              \"bicfi\": \"IJKLMNOPXXX\",\n"
            + "              \"othr\": {\n"
            + "                \"id\": \"ABCDEFGHXXX\"\n"
            + "              }\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"to\": {\n"
            + "          \"fiId\": {\n"
            + "            \"finInstnId\": {\n"
            + "              \"bicfi\": \"ABCDEFGHXXX\",\n"
            + "              \"othr\": {\n"
            + "                \"id\": \"ABCDEFGHXXX\"\n"
            + "              }\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"bizMsgIdr\": \"1423905641002\",\n"
            + "        \"msgDefIdr\": \"sese.025.001.09\",\n"
            + "        \"creDt\": {\n"
            + "          \"dateTime\": {\n"
            + "            \"date\": {\n"
            + "              \"year\": 2024,\n"
            + "              \"month\": 7,\n"
            + "              \"day\": 17\n"
            + "            },\n"
            + "            \"time\": {\n"
            + "              \"hour\": 5,\n"
            + "              \"minute\": 27,\n"
            + "              \"second\": 51,\n"
            + "              \"nano\": 0\n"
            + "            }\n"
            + "          },\n"
            + "          \"offset\": {\n"
            + "            \"totalSeconds\": 0\n"
            + "          }\n"
            + "        },\n"
            + "        \"cpyDplct\": \"COPY\",\n"
            + "        \"pssblDplct\": true,\n"
            + "        \"prty\": \"2024071700000208\",\n"
            + "        \"namespace\": \"urn:iso:std:iso:20022:tech:xsd:head.001.001.01\"\n"
            + "      },\n"
            + "      \"type\": \"MX\",\n"
            + "      \"@xmlns\": \"urn:iso:std:iso:20022:tech:xsd:sese.025.001.09\",\n"
            + "      \"identifier\": \"sese.025.001.09\"\n"
            + "    }";

    @Test
    void v10_should_be_able_to_parse_json_with_date_time_created_from_v9() {
        final MxSese02500109 mx = (MxSese02500109) AbstractMX.fromJson(JSON_MX_V9);
        assertThat(mx.getSctiesSttlmTxConf().getTradDtls().getTradDt().getDt().getDt())
                .isNotNull(); // Success
        assertThat(mx.getSctiesSttlmTxConf()
                        .getTradDtls()
                        .getFctvSttlmDt()
                        .getDt()
                        .getDtTm())
                .isNotNull(); // Fail
    }

    @Test
    void v10_should_be_able_to_parse_json_from_v9_and_read_same_content_than_json_from_v10_and_xml() {
        final MxSese02500109 reference = (MxSese02500109) AbstractMX.parse(XML_MX);
        final MxSese02500109 fromV9 = (MxSese02500109) AbstractMX.fromJson(JSON_MX_V9);
        final String toV10 = reference.toJson();
        final MxSese02500109 fromV10 = (MxSese02500109) AbstractMX.fromJson(JSON_MX_V10);

        assertThat(fromV9).isEqualTo(reference);
        assertThat(fromV10).isEqualTo(reference);
        assertThat(fromV9).isEqualTo(fromV10);
        assertThat(toV10).isEqualToIgnoringWhitespace(JSON_MX_V10);
        assertThat(toV10).isNotEqualToIgnoringWhitespace(JSON_MX_V9);
    }
}
