package com.prowidesoftware.swift.model.mx.adapters;

import static org.assertj.core.api.Assertions.assertThat;

import com.prowidesoftware.swift.model.mx.AbstractMX;
import com.prowidesoftware.swift.model.mx.BusinessAppHdrV01;
import com.prowidesoftware.swift.model.mx.MxSese02500109;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.DisplayNameGeneration;
import org.junit.jupiter.api.DisplayNameGenerator;
import org.junit.jupiter.api.Test;

@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
class DateTimeJsonAdapterBackwardCompatibilityTest {

    private static final String JSON_MX_V9 = "{\n" + "      \"sctiesSttlmTxConf\": {\n"
            + "        \"txIdDtls\": {\n"
            + "          \"acctOwnrTxId\": \"FOO\",\n"
            + "          \"mktInfrstrctrTxId\": \"BAR\",\n"
            + "          \"prcrTxId\": \"TOTO\",\n"
            + "          \"sctiesMvmntTp\": \"RECE\",\n"
            + "          \"pmt\": \"APMT\",\n"
            + "          \"cmonId\": \"TITI\"\n"
            + "        },\n"
            + "        \"tradDtls\": {\n"
            + "          \"plcOfTrad\": {\n"
            + "            \"mktTpAndId\": {\n"
            + "              \"tp\": {\n"
            + "                \"cd\": \"EXCH\"\n"
            + "              }\n"
            + "            }\n"
            + "          },\n"
            + "          \"plcOfClr\": {\n"
            + "            \"id\": \"QRSTUVWYXXX\"\n"
            + "          },\n"
            + "          \"tradDt\": {\n"
            + "            \"dt\": {\n"
            + "              \"dt\": {\n"
            + "                \"year\": 2024,\n"
            + "                \"month\": 7,\n"
            + "                \"day\": 16,\n"
            + "                \"timezone\": -2147483648,\n"
            + "                \"hour\": -2147483648,\n"
            + "                \"minute\": -2147483648,\n"
            + "                \"second\": -2147483648\n"
            + "              }\n"
            + "            }\n"
            + "          },\n"
            + "          \"sttlmDt\": {\n"
            + "            \"dt\": {\n"
            + "              \"dt\": {\n"
            + "                \"year\": 2024,\n"
            + "                \"month\": 7,\n"
            + "                \"day\": 17,\n"
            + "                \"timezone\": -2147483648,\n"
            + "                \"hour\": -2147483648,\n"
            + "                \"minute\": -2147483648,\n"
            + "                \"second\": -2147483648\n"
            + "              }\n"
            + "            }\n"
            + "          },\n"
            + "          \"fctvSttlmDt\": {\n"
            + "            \"dt\": {\n"
            + "              \"dtTm\": {\n"
            + "                \"year\": 2024,\n"
            + "                \"month\": 7,\n"
            + "                \"day\": 17,\n"
            + "                \"timezone\": 120,\n" // this is UTC +02:00
            + "                \"hour\": 7,\n"
            + "                \"minute\": 26,\n"
            + "                \"second\": 4,\n"
            + "                \"fractionalSecond\": 0.207459\n"
            + "              }\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"finInstrmId\": {\n"
            + "          \"isin\": \"NL0000009165\"\n"
            + "        },\n"
            + "        \"qtyAndAcctDtls\": {\n"
            + "          \"sttldQty\": {\n"
            + "            \"qty\": {\n"
            + "              \"unit\": 0\n"
            + "            }\n"
            + "          },\n"
            + "          \"sfkpgAcct\": {\n"
            + "            \"id\": \"NECISOGEFRPPAGN000L10\"\n"
            + "          },\n"
            + "          \"cshAcct\": {\n"
            + "            \"prtry\": \"CFREURSOGEFRPPTIT-DCA-SGSS\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"sttlmParams\": {\n"
            + "          \"sctiesTxTp\": {\n"
            + "            \"cd\": \"NETT\"\n"
            + "          },\n"
            + "          \"prtlSttlmInd\": \"PARQ\",\n"
            + "          \"cshSubBalTp\": {\n"
            + "            \"id\": \"DLVR\",\n"
            + "            \"issr\": \"T2S\",\n"
            + "            \"schmeNm\": \"RT\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"dlvrgSttlmPties\": {\n"
            + "          \"dpstry\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"ABCDEFGHXXX\"\n"
            + "            },\n"
            + "            \"prcgId\": \"2407162881091741\"\n"
            + "          },\n"
            + "          \"pty1\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"QRSTUVWYXXX\"\n"
            + "            },\n"
            + "            \"sfkpgAcct\": {\n"
            + "              \"id\": \"MOTICCEGITRRXXX9100000\"\n"
            + "            },\n"
            + "            \"prcgId\": \"1VUVZK\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"rcvgSttlmPties\": {\n"
            + "          \"dpstry\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"HGFEDCBAXXX\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"pty1\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"SOGEFRPPAGN\"\n"
            + "            },\n"
            + "            \"sfkpgAcct\": {\n"
            + "              \"id\": \"NECISOGEFRPPAGN000L10\"\n"
            + "            },\n"
            + "            \"prcgId\": \"FOO\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"sttldAmt\": {\n"
            + "          \"amt\": {\n"
            + "            \"value\": 1,\n"
            + "            \"ccy\": \"EUR\"\n"
            + "          },\n"
            + "          \"cdtDbtInd\": \"DBIT\"\n"
            + "        },\n"
            + "        \"splmtryData\": [\n"
            + "          {\n"
            + "            \"plcAndNm\": \"/Document/SctiesSttlmTxConf/TxIdDtls\",\n"
            + "            \"envlp\": {}\n"
            + "          }\n"
            + "        ]\n"
            + "      },\n"
            + "      \"appHdr\": {\n"
            + "        \"fr\": {\n"
            + "          \"fiId\": {\n"
            + "            \"finInstnId\": {\n"
            + "              \"bicfi\": \"IJKLMNOPXXX\",\n"
            + "              \"othr\": {\n"
            + "                \"id\": \"ABCDEFGHXXX\"\n"
            + "              }\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"to\": {\n"
            + "          \"fiId\": {\n"
            + "            \"finInstnId\": {\n"
            + "              \"bicfi\": \"ABCDEFGHXXX\",\n"
            + "              \"othr\": {\n"
            + "                \"id\": \"ABCDEFGHXXX\"\n"
            + "              }\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"bizMsgIdr\": \"1423905641002\",\n"
            + "        \"msgDefIdr\": \"sese.025.001.09\",\n"
            + "        \"creDt\": {\n"
            + "          \"year\": 2024,\n"
            + "          \"month\": 7,\n"
            + "          \"day\": 17,\n"
            + "          \"timezone\": 0,\n" // UTC 0
            + "          \"hour\": 5,\n"
            + "          \"minute\": 27,\n"
            + "          \"second\": 51\n"
            + "        },\n"
            + "        \"cpyDplct\": \"COPY\",\n"
            + "        \"pssblDplct\": true,\n"
            + "        \"prty\": \"2024071700000208\",\n"
            + "        \"namespace\": \"urn:iso:std:iso:20022:tech:xsd:head.001.001.01\"\n"
            + "      },\n"
            + "      \"type\": \"MX\",\n"
            + "      \"@xmlns\": \"urn:iso:std:iso:20022:tech:xsd:sese.025.001.09\",\n"
            + "      \"identifier\": \"sese.025.001.09\"\n"
            + "    }";

    private static final String JSON_MX_V10 = "{\n" + "      \"sctiesSttlmTxConf\": {\n"
            + "        \"txIdDtls\": {\n"
            + "          \"acctOwnrTxId\": \"FOO\",\n"
            + "          \"mktInfrstrctrTxId\": \"BAR\",\n"
            + "          \"prcrTxId\": \"TOTO\",\n"
            + "          \"sctiesMvmntTp\": \"RECE\",\n"
            + "          \"pmt\": \"APMT\",\n"
            + "          \"cmonId\": \"TITI\"\n"
            + "        },\n"
            + "        \"tradDtls\": {\n"
            + "          \"plcOfTrad\": {\n"
            + "            \"mktTpAndId\": {\n"
            + "              \"tp\": {\n"
            + "                \"cd\": \"EXCH\"\n"
            + "              }\n"
            + "            }\n"
            + "          },\n"
            + "          \"plcOfClr\": {\n"
            + "            \"id\": \"QRSTUVWYXXX\"\n"
            + "          },\n"
            + "          \"tradDt\": {\n"
            + "            \"dt\": {\n"
            + "              \"dt\": {\n"
            + "                \"year\": 2024,\n"
            + "                \"month\": 7,\n"
            + "                \"day\": 16\n"
            + "              }\n"
            + "            }\n"
            + "          },\n"
            + "          \"sttlmDt\": {\n"
            + "            \"dt\": {\n"
            + "              \"dt\": {\n"
            + "                \"year\": 2024,\n"
            + "                \"month\": 7,\n"
            + "                \"day\": 17\n"
            + "              }\n"
            + "            }\n"
            + "          },\n"
            + "          \"fctvSttlmDt\": {\n"
            + "            \"dt\": {\n"
            + "              \"dtTm\": {\n"
            + "                \"dateTime\": {\n"
            + "                  \"date\": {\n"
            + "                    \"year\": 2024,\n"
            + "                    \"month\": 7,\n"
            + "                    \"day\": 17\n"
            + "                  },\n"
            + "                  \"time\": {\n"
            + "                    \"hour\": 7,\n"
            + "                    \"minute\": 26,\n"
            + "                    \"second\": 4,\n"
            + "                    \"nano\": 207459000\n"
            + "                  }\n"
            + "                },\n"
            + "                \"offset\": {\n"
            + "                  \"totalSeconds\": 7200\n" // this is UTC +02:00
            + "                }\n"
            + "              }\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"finInstrmId\": {\n"
            + "          \"isin\": \"NL0000009165\"\n"
            + "        },\n"
            + "        \"qtyAndAcctDtls\": {\n"
            + "          \"sttldQty\": {\n"
            + "            \"qty\": {\n"
            + "              \"unit\": 0\n"
            + "            }\n"
            + "          },\n"
            + "          \"sfkpgAcct\": {\n"
            + "            \"id\": \"NECISOGEFRPPAGN000L10\"\n"
            + "          },\n"
            + "          \"cshAcct\": {\n"
            + "            \"prtry\": \"CFREURSOGEFRPPTIT-DCA-SGSS\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"sttlmParams\": {\n"
            + "          \"sctiesTxTp\": {\n"
            + "            \"cd\": \"NETT\"\n"
            + "          },\n"
            + "          \"prtlSttlmInd\": \"PARQ\",\n"
            + "          \"cshSubBalTp\": {\n"
            + "            \"id\": \"DLVR\",\n"
            + "            \"issr\": \"T2S\",\n"
            + "            \"schmeNm\": \"RT\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"dlvrgSttlmPties\": {\n"
            + "          \"dpstry\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"ABCDEFGHXXX\"\n"
            + "            },\n"
            + "            \"prcgId\": \"2407162881091741\"\n"
            + "          },\n"
            + "          \"pty1\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"QRSTUVWYXXX\"\n"
            + "            },\n"
            + "            \"sfkpgAcct\": {\n"
            + "              \"id\": \"MOTICCEGITRRXXX9100000\"\n"
            + "            },\n"
            + "            \"prcgId\": \"1VUVZK\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"rcvgSttlmPties\": {\n"
            + "          \"dpstry\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"HGFEDCBAXXX\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"pty1\": {\n"
            + "            \"id\": {\n"
            + "              \"anyBIC\": \"SOGEFRPPAGN\"\n"
            + "            },\n"
            + "            \"sfkpgAcct\": {\n"
            + "              \"id\": \"NECISOGEFRPPAGN000L10\"\n"
            + "            },\n"
            + "            \"prcgId\": \"FOO\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"sttldAmt\": {\n"
            + "          \"amt\": {\n"
            + "            \"value\": 1,\n"
            + "            \"ccy\": \"EUR\"\n"
            + "          },\n"
            + "          \"cdtDbtInd\": \"DBIT\"\n"
            + "        },\n"
            + "        \"splmtryData\": [\n"
            + "          {\n"
            + "            \"plcAndNm\": \"/Document/SctiesSttlmTxConf/TxIdDtls\",\n"
            + "            \"envlp\": {}\n"
            + "          }\n"
            + "        ]\n"
            + "      },\n"
            + "      \"appHdr\": {\n"
            + "        \"fr\": {\n"
            + "          \"fiId\": {\n"
            + "            \"finInstnId\": {\n"
            + "              \"bicfi\": \"IJKLMNOPXXX\",\n"
            + "              \"othr\": {\n"
            + "                \"id\": \"ABCDEFGHXXX\"\n"
            + "              }\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"to\": {\n"
            + "          \"fiId\": {\n"
            + "            \"finInstnId\": {\n"
            + "              \"bicfi\": \"ABCDEFGHXXX\",\n"
            + "              \"othr\": {\n"
            + "                \"id\": \"ABCDEFGHXXX\"\n"
            + "              }\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"bizMsgIdr\": \"1423905641002\",\n"
            + "        \"msgDefIdr\": \"sese.025.001.09\",\n"
            + "        \"creDt\": {\n"
            + "          \"dateTime\": {\n"
            + "            \"date\": {\n"
            + "              \"year\": 2024,\n"
            + "              \"month\": 7,\n"
            + "              \"day\": 17\n"
            + "            },\n"
            + "            \"time\": {\n"
            + "              \"hour\": 5,\n"
            + "              \"minute\": 27,\n"
            + "              \"second\": 51,\n"
            + "              \"nano\": 0\n"
            + "            }\n"
            + "          },\n"
            + "          \"offset\": {\n"
            + "            \"totalSeconds\": 0\n" // UTC 0
            + "          }\n"
            + "        },\n"
            + "        \"cpyDplct\": \"COPY\",\n"
            + "        \"pssblDplct\": true,\n"
            + "        \"prty\": \"2024071700000208\",\n"
            + "        \"namespace\": \"urn:iso:std:iso:20022:tech:xsd:head.001.001.01\"\n"
            + "      },\n"
            + "      \"type\": \"MX\",\n"
            + "      \"@xmlns\": \"urn:iso:std:iso:20022:tech:xsd:sese.025.001.09\",\n"
            + "      \"identifier\": \"sese.025.001.09\"\n"
            + "    }";

    @Test
    void shouldBeAbleToParseJsonFromLegacyXMLGregorianCalendar() {
        final MxSese02500109 mx = (MxSese02500109) AbstractMX.fromJson(JSON_MX_V9);

        assertThat(mx.getSctiesSttlmTxConf().getTradDtls().getTradDt().getDt().getDt())
                .isNotNull();

        OffsetDateTime dateTime =
                mx.getSctiesSttlmTxConf().getTradDtls().getFctvSttlmDt().getDt().getDtTm();
        assertThat(dateTime).isNotNull();
        assertThat(dateTime.getYear()).isEqualTo(2024);
        assertThat(dateTime.getMonthValue()).isEqualTo(7);
        assertThat(dateTime.getDayOfMonth()).isEqualTo(17);
        assertThat(dateTime.getHour()).isEqualTo(7);
        assertThat(dateTime.getMinute()).isEqualTo(26);
        assertThat(dateTime.getSecond()).isEqualTo(4);
        assertThat(dateTime.getNano()).isEqualTo(207459000);
    }

    @Test
    void allParsedDateTimeObjectsShouldMatch() {
        final MxSese02500109 fromV9 = (MxSese02500109) AbstractMX.fromJson(JSON_MX_V9);
        final MxSese02500109 fromV10 = (MxSese02500109) AbstractMX.fromJson(JSON_MX_V10);

        LocalDate tradDtV9 =
                fromV9.getSctiesSttlmTxConf().getTradDtls().getTradDt().getDt().getDt();
        LocalDate tradDtV10 =
                fromV10.getSctiesSttlmTxConf().getTradDtls().getTradDt().getDt().getDt();
        assertThat(tradDtV9).isEqualTo(tradDtV10);

        LocalDate sttlmDtV9 =
                fromV9.getSctiesSttlmTxConf().getTradDtls().getSttlmDt().getDt().getDt();
        LocalDate sttlmDtV10 = fromV10.getSctiesSttlmTxConf()
                .getTradDtls()
                .getSttlmDt()
                .getDt()
                .getDt();
        assertThat(sttlmDtV9).isEqualTo(sttlmDtV10);

        OffsetDateTime fctvSttlmDtV9 = fromV9.getSctiesSttlmTxConf()
                .getTradDtls()
                .getFctvSttlmDt()
                .getDt()
                .getDtTm();
        OffsetDateTime fctvSttlmDtV10 = fromV10.getSctiesSttlmTxConf()
                .getTradDtls()
                .getFctvSttlmDt()
                .getDt()
                .getDtTm();
        assertThat(fctvSttlmDtV9).isEqualTo(fctvSttlmDtV10);

        OffsetDateTime creDtV9 = ((BusinessAppHdrV01) fromV9.getAppHdr()).getCreDt();
        OffsetDateTime creDtV10 = ((BusinessAppHdrV01) fromV10.getAppHdr()).getCreDt();
        assertThat(creDtV9).isEqualTo(creDtV10);
    }
}
