/*
 * Copyright 2006-2024 Prowide
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.prowidesoftware.swift.model.mx;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.prowidesoftware.swift.model.MxId;
import org.junit.jupiter.api.Test;

/**
 * Test for JSON conversion in the MX model (AbstractMX and subclasses).
 *
 * @since 7.10.2
 */
public class AbstractMxJsonV9Test {

    String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
            + "<Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns=\"urn:swift:xsd:envelope\""
            + "          xsi:schemaLocation=\"urn:swift:xsd:envelope ../../../../Schemas/Translator_envelope.xsd\">"
            + "    <AppHdr xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
            + "            xmlns=\"urn:iso:std:iso:20022:tech:xsd:head.001.001.02\">"
            + "        <Fr>"
            + "            <FIId>"
            + "                <FinInstnId>"
            + "                    <BICFI>FOORUS33</BICFI>"
            + "                </FinInstnId>"
            + "            </FIId>"
            + "        </Fr>"
            + "        <To>"
            + "            <FIId>"
            + "                <FinInstnId>"
            + "                    <BICFI>FOORGB2L</BICFI>"
            + "                </FinInstnId>"
            + "            </FIId>"
            + "        </To>"
            + "        <BizMsgIdr>pacs009bizmsgidr-001</BizMsgIdr>"
            + "        <MsgDefIdr>pacs.009.001.08CORE</MsgDefIdr>"
            + "        <BizSvc>swift.cbprplus.cov.02</BizSvc>"
            + "        <CreDt>2020-12-14T09:00:00-04:00</CreDt>"
            + "    </AppHdr>"
            + "    <Document xmlns=\"urn:iso:std:iso:20022:tech:xsd:pacs.009.001.08\">"
            + "        <FICdtTrf>"
            + "            <GrpHdr>"
            + "                <MsgId>pacs009bizmsgidr-001</MsgId>"
            + "                <CreDtTm>2020-12-14T09:12:54.412-04:00</CreDtTm>"
            + "                <NbOfTxs>1</NbOfTxs>"
            + "                <SttlmInf>"
            + "                    <SttlmMtd>INDA</SttlmMtd>"
            + "                </SttlmInf>"
            + "            </GrpHdr>"
            + "            <CdtTrfTxInf>"
            + "                <PmtId>"
            + "                    <InstrId>pcsdrId00a</InstrId>"
            + "                    <EndToEndId>pacs009EndToEndId-001</EndToEndId>"
            + "                    <UETR>2f876d32-df01-44ef-b925-34418eb3a998</UETR>"
            + "                </PmtId>"
            + "                <IntrBkSttlmAmt Ccy=\"GBP\">100000000</IntrBkSttlmAmt>"
            + "                <IntrBkSttlmDt>2020-12-14</IntrBkSttlmDt>"
            + "                <InstgAgt>"
            + "                    <FinInstnId>"
            + "                        <BICFI>FOORUS33</BICFI>"
            + "                    </FinInstnId>"
            + "                </InstgAgt>"
            + "                <InstdAgt>"
            + "                    <FinInstnId>"
            + "                        <BICFI>FOORGB2L</BICFI>"
            + "                    </FinInstnId>"
            + "                </InstdAgt>"
            + "                <Dbtr>"
            + "                    <FinInstnId>"
            + "                        <BICFI>FOORUS33</BICFI>"
            + "                    </FinInstnId>"
            + "                </Dbtr>"
            + "                <Cdtr>"
            + "                    <FinInstnId>"
            + "                        <BICFI>FOOYGB2L</BICFI>"
            + "                    </FinInstnId>"
            + "                </Cdtr>"
            + "                <UndrlygCstmrCdtTrf>"
            + "                    <UltmtDbtr>"
            + "                        <Nm>GOLDMANS</Nm>"
            + "                        <PstlAdr>"
            + "                            <StrtNm>5TH AVENUE</StrtNm>"
            + "                            <TwnNm>New York</TwnNm>"
            + "                            <Ctry>US</Ctry>"
            + "                        </PstlAdr>"
            + "                    </UltmtDbtr>"
            + "                    <InitgPty>"
            + "                        <Nm>Virgay</Nm>"
            + "                        <PstlAdr>"
            + "                            <StrtNm>Virginia Lane</StrtNm>"
            + "                            <BldgNb>36</BldgNb>"
            + "                            <PstCd>NJ 07311</PstCd>"
            + "                            <TwnNm>Jersey City</TwnNm>"
            + "                            <Ctry>US</Ctry>"
            + "                        </PstlAdr>"
            + "                    </InitgPty>"
            + "                    <Dbtr>"
            + "                        <Nm>GOLDMANS</Nm>"
            + "                        <PstlAdr>"
            + "                            <StrtNm>5TH AVENUE</StrtNm>"
            + "                            <TwnNm>New York</TwnNm>"
            + "                            <Ctry>US</Ctry>"
            + "                        </PstlAdr>"
            + "                    </Dbtr>"
            + "                    <DbtrAgt>"
            + "                        <FinInstnId>"
            + "                            <BICFI>FOORUS33</BICFI>"
            + "                        </FinInstnId>"
            + "                    </DbtrAgt>"
            + "                    <CdtrAgt>"
            + "                        <FinInstnId>"
            + "                            <BICFI>FOOYGB2L</BICFI>"
            + "                        </FinInstnId>"
            + "                    </CdtrAgt>"
            + "                    <Cdtr>"
            + "                        <Nm>SMITHSON</Nm>"
            + "                        <PstlAdr>"
            + "                            <StrtNm>LONDON WALL</StrtNm>"
            + "                            <TwnNm>LONDON</TwnNm>"
            + "                            <Ctry>GB</Ctry>"
            + "                        </PstlAdr>"
            + "                    </Cdtr>"
            + "                </UndrlygCstmrCdtTrf>"
            + "            </CdtTrfTxInf>"
            + "        </FICdtTrf>"
            + "    </Document>"
            + "</Envelope>";

    String jsonV10 = "{" + "  'fiCdtTrf': {"
            + "    'grpHdr': {"
            + "      'msgId': 'pacs009bizmsgidr-001',"
            + "      'creDtTm': {"
            + "        'dateTime': {"
            + "          'date': {"
            + "            'year': 2020,"
            + "            'month': 12,"
            + "            'day': 14"
            + "          },"
            + "          'time': {"
            + "            'hour': 9,"
            + "            'minute': 12,"
            + "            'second': 54,"
            + "            'nano': 412000000"
            + "          }"
            + "        },"
            + "        'offset': {"
            + "          'totalSeconds': -14400"
            + "        }"
            + "      },"
            + "      'nbOfTxs': '1',"
            + "      'sttlmInf': {"
            + "        'sttlmMtd': 'INDA'"
            + "      }"
            + "    },"
            + "    'cdtTrfTxInf': ["
            + "      {"
            + "        'pmtId': {"
            + "          'instrId': 'pcsdrId00a',"
            + "          'endToEndId': 'pacs009EndToEndId-001',"
            + "          'uetr': '2f876d32-df01-44ef-b925-34418eb3a998'"
            + "        },"
            + "        'intrBkSttlmAmt': {"
            + "          'value': 100000000,"
            + "          'ccy': 'GBP'"
            + "        },"
            + "        'intrBkSttlmDt': {"
            + "          'year': 2020,"
            + "          'month': 12,"
            + "          'day': 14"
            + "        },"
            + "        'instgAgt': {"
            + "          'finInstnId': {"
            + "            'bicfi': 'FOORUS33'"
            + "          }"
            + "        },"
            + "        'instdAgt': {"
            + "          'finInstnId': {"
            + "            'bicfi': 'FOORGB2L'"
            + "          }"
            + "        },"
            + "        'dbtr': {"
            + "          'finInstnId': {"
            + "            'bicfi': 'FOORUS33'"
            + "          }"
            + "        },"
            + "        'cdtr': {"
            + "          'finInstnId': {"
            + "            'bicfi': 'FOOYGB2L'"
            + "          }"
            + "        },"
            + "        'undrlygCstmrCdtTrf': {"
            + "          'ultmtDbtr': {"
            + "            'nm': 'GOLDMANS',"
            + "            'pstlAdr': {"
            + "              'strtNm': '5TH AVENUE',"
            + "              'twnNm': 'New York',"
            + "              'ctry': 'US'"
            + "            }"
            + "          },"
            + "          'initgPty': {"
            + "            'nm': 'Virgay',"
            + "            'pstlAdr': {"
            + "              'strtNm': 'Virginia Lane',"
            + "              'bldgNb': '36',"
            + "              'pstCd': 'NJ 07311',"
            + "              'twnNm': 'Jersey City',"
            + "              'ctry': 'US'"
            + "            }"
            + "          },"
            + "          'dbtr': {"
            + "            'nm': 'GOLDMANS',"
            + "            'pstlAdr': {"
            + "              'strtNm': '5TH AVENUE',"
            + "              'twnNm': 'New York',"
            + "              'ctry': 'US'"
            + "            }"
            + "          },"
            + "          'dbtrAgt': {"
            + "            'finInstnId': {"
            + "              'bicfi': 'FOORUS33'"
            + "            }"
            + "          },"
            + "          'cdtrAgt': {"
            + "            'finInstnId': {"
            + "              'bicfi': 'FOOYGB2L'"
            + "            }"
            + "          },"
            + "          'cdtr': {"
            + "            'nm': 'SMITHSON',"
            + "            'pstlAdr': {"
            + "              'strtNm': 'LONDON WALL',"
            + "              'twnNm': 'LONDON',"
            + "              'ctry': 'GB'"
            + "            }"
            + "          }"
            + "        }"
            + "      }"
            + "    ]"
            + "  },"
            + "  'appHdr': {"
            + "    'fr': {"
            + "      'fiId': {"
            + "        'finInstnId': {"
            + "          'bicfi': 'FOORUS33'"
            + "        }"
            + "      }"
            + "    },"
            + "    'to': {"
            + "      'fiId': {"
            + "        'finInstnId': {"
            + "          'bicfi': 'FOORGB2L'"
            + "        }"
            + "      }"
            + "    },"
            + "    'bizMsgIdr': 'pacs009bizmsgidr-001',"
            + "    'msgDefIdr': 'pacs.009.001.08CORE',"
            + "    'bizSvc': 'swift.cbprplus.cov.02',"
            + "    'creDt': {"
            + "      'dateTime': {"
            + "        'date': {"
            + "          'year': 2020,"
            + "          'month': 12,"
            + "          'day': 14"
            + "        },"
            + "        'time': {"
            + "          'hour': 9,"
            + "          'minute': 0,"
            + "          'second': 0,"
            + "          'nano': 0"
            + "        }"
            + "      },"
            + "      'offset': {"
            + "        'totalSeconds': -14400"
            + "      }"
            + "    },"
            + "    'namespace': 'urn:iso:std:iso:20022:tech:xsd:head.001.001.02'"
            + "  },"
            + "  'type': 'MX',"
            + "  '@xmlns': 'urn:iso:std:iso:20022:tech:xsd:pacs.009.001.08',"
            + "  'identifier': 'pacs.009.001.08'"
            + "}";

    String jsonV9 = "{" + "  'fiCdtTrf': {"
            + "    'grpHdr': {"
            + "      'msgId': 'pacs009bizmsgidr-001',"
            + "      'creDtTm': {"
            + "        'year': 2020,"
            + "        'month': 12,"
            + "        'day': 14,"
            + "        'timezone': -240,"
            + "        'hour': 9,"
            + "        'minute': 12,"
            + "        'second': 54,"
            + "        'fractionalSecond': 0.412"
            + "      },"
            + "      'nbOfTxs': '1',"
            + "      'sttlmInf': {"
            + "        'sttlmMtd': 'INDA'"
            + "      }"
            + "    },"
            + "    'cdtTrfTxInf': ["
            + "      {"
            + "        'pmtId': {"
            + "          'instrId': 'pcsdrId00a',"
            + "          'endToEndId': 'pacs009EndToEndId-001',"
            + "          'uetr': '2f876d32-df01-44ef-b925-34418eb3a998'"
            + "        },"
            + "        'intrBkSttlmAmt': {"
            + "          'value': 100000000,"
            + "          'ccy': 'GBP'"
            + "        },"
            + "        'intrBkSttlmDt': {"
            + "          'year': 2020,"
            + "          'month': 12,"
            + "          'day': 14"
            + "        },"
            + "        'instgAgt': {"
            + "          'finInstnId': {"
            + "            'bicfi': 'FOORUS33'"
            + "          }"
            + "        },"
            + "        'instdAgt': {"
            + "          'finInstnId': {"
            + "            'bicfi': 'FOORGB2L'"
            + "          }"
            + "        },"
            + "        'dbtr': {"
            + "          'finInstnId': {"
            + "            'bicfi': 'FOORUS33'"
            + "          }"
            + "        },"
            + "        'cdtr': {"
            + "          'finInstnId': {"
            + "            'bicfi': 'FOOYGB2L'"
            + "          }"
            + "        },"
            + "        'undrlygCstmrCdtTrf': {"
            + "          'ultmtDbtr': {"
            + "            'nm': 'GOLDMANS',"
            + "            'pstlAdr': {"
            + "              'strtNm': '5TH AVENUE',"
            + "              'twnNm': 'New York',"
            + "              'ctry': 'US'"
            + "            }"
            + "          },"
            + "          'initgPty': {"
            + "            'nm': 'Virgay',"
            + "            'pstlAdr': {"
            + "              'strtNm': 'Virginia Lane',"
            + "              'bldgNb': '36',"
            + "              'pstCd': 'NJ 07311',"
            + "              'twnNm': 'Jersey City',"
            + "              'ctry': 'US'"
            + "            }"
            + "          },"
            + "          'dbtr': {"
            + "            'nm': 'GOLDMANS',"
            + "            'pstlAdr': {"
            + "              'strtNm': '5TH AVENUE',"
            + "              'twnNm': 'New York',"
            + "              'ctry': 'US'"
            + "            }"
            + "          },"
            + "          'dbtrAgt': {"
            + "            'finInstnId': {"
            + "              'bicfi': 'FOORUS33'"
            + "            }"
            + "          },"
            + "          'cdtrAgt': {"
            + "            'finInstnId': {"
            + "              'bicfi': 'FOOYGB2L'"
            + "            }"
            + "          },"
            + "          'cdtr': {"
            + "            'nm': 'SMITHSON',"
            + "            'pstlAdr': {"
            + "              'strtNm': 'LONDON WALL',"
            + "              'twnNm': 'LONDON',"
            + "              'ctry': 'GB'"
            + "            }"
            + "          }"
            + "        }"
            + "      }"
            + "    ]"
            + "  },"
            + "  'appHdr': {"
            + "    'fr': {"
            + "      'fiId': {"
            + "        'finInstnId': {"
            + "          'bicfi': 'FOORUS33'"
            + "        }"
            + "      }"
            + "    },"
            + "    'to': {"
            + "      'fiId': {"
            + "        'finInstnId': {"
            + "          'bicfi': 'FOORGB2L'"
            + "        }"
            + "      }"
            + "    },"
            + "    'bizMsgIdr': 'pacs009bizmsgidr-001',"
            + "    'msgDefIdr': 'pacs.009.001.08CORE',"
            + "    'bizSvc': 'swift.cbprplus.cov.02',"
            + "    'creDt': {"
            + "      'year': 2020,"
            + "      'month': 12,"
            + "      'day': 14,"
            + "      'timezone': -240,"
            + "      'hour': 9,"
            + "      'minute': 0,"
            + "      'second': 0,"
            + "      'fractionalSecond': 0"
            + "    },"
            + "    'namespace': 'urn:iso:std:iso:20022:tech:xsd:head.001.001.02'"
            + "  },"
            + "  'type': 'MX',"
            + "  '@xmlns': 'urn:iso:std:iso:20022:tech:xsd:pacs.009.001.08',"
            + "  'identifier': 'pacs.009.001.08'"
            + "}";

    @Test
    public void testMxToJson() {
        AbstractMX mx = MxPacs00900108.parse(xml, new MxId("pacs.009.001.08"));

        String v10Json = mx.toJson();
        assertTrue(v10Json.contains("\"totalSeconds\": -14400"));
        assertTrue(v10Json.contains("\"nano\": 412000000"));

        String v9Json = mx.toJsonV9();
        assertTrue(v9Json.contains("\"timezone\": -240"));
        assertTrue(v9Json.contains("\"fractionalSecond\": 0.412"));
    }

    @Test
    public void testMxFromJsonV10() {
        MxPacs00900108 mxFromJson = MxPacs00900108.fromJson(jsonV10);
        MxPacs00900108 mx = (MxPacs00900108) MxPacs00900108.parse(xml, new MxId("pacs.009.001.08"));
        assertEquals(mx.message(), mxFromJson.message());
    }

    @Test
    public void testMxFromJsonV9() {
        AbstractMX mxFromJson = MxPacs00900108.fromJsonV9(jsonV9);
        AbstractMX mx = MxPacs00900108.parse(xml, new MxId("pacs.009.001.08"));
        assertEquals(mx.message(), mxFromJson.message());
    }
}
