/*
 * Copyright 2006-2023 Prowide
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.prowidesoftware.swift.model.mx;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

/**
 * @since 9.0.1
 */
public class BusinessAppHdrV02Test {

    @Test
    public void testParseNoNamespace() {
        final String xml = "<AppHdr>" + "   <Fr>"
                + "      <FIId>"
                + "         <FinInstnId>"
                + "            <Nm>Not available</Nm>"
                + "         </FinInstnId>"
                + "      </FIId>"
                + "   </Fr>"
                + "   <To>"
                + "      <FIId>"
                + "         <FinInstnId>"
                + "            <Nm>Not available</Nm>"
                + "         </FinInstnId>"
                + "      </FIId>"
                + "   </To>"
                + "   <BizMsgIdr>AAAAAAAAAA222222</BizMsgIdr>"
                + "   <MsgDefIdr>seev.037.002.02</MsgDefIdr>"
                + "   <MktPrctc>"
                + "       <Regy>FOO</Regy>"
                + "       <Id>BAR</Id>·+"
                + "   </MktPrctc>"
                + "   <CreDt>2017-08-08T16:58:01Z</CreDt>"
                + "</AppHdr>";
        BusinessAppHdrV02 h = BusinessAppHdrV02.parse(xml);
        assertNotNull(h);
        // System.out.println(h.xml());
        assertEquals("Not available", h.getFr().getFIId().getFinInstnId().getNm());
        assertEquals("Not available", h.getTo().getFIId().getFinInstnId().getNm());
        assertEquals("AAAAAAAAAA222222", h.getBizMsgIdr());
        assertEquals("seev.037.002.02", h.getMsgDefIdr());
        assertEquals("FOO", h.getMktPrctc().getRegy());
        assertEquals("BAR", h.getMktPrctc().getId());
        assertNotNull(h.getCreDt());
    }

    @Test
    public void testParseNoPrefix() {
        final String xml = "<AppHdr xmlns=\"urn:iso:std:iso:20022:tech:xsd:head.001.001.02\">" + "   <Fr>"
                + "      <FIId>"
                + "         <FinInstnId>"
                + "            <Nm>Not available</Nm>"
                + "         </FinInstnId>"
                + "      </FIId>"
                + "   </Fr>"
                + "   <To>"
                + "      <FIId>"
                + "         <FinInstnId>"
                + "            <Nm>Not available</Nm>"
                + "         </FinInstnId>"
                + "      </FIId>"
                + "   </To>"
                + "   <BizMsgIdr>AAAAAAAAAA222222</BizMsgIdr>"
                + "   <MsgDefIdr>seev.037.002.02</MsgDefIdr>"
                + "   <MktPrctc>"
                + "       <Regy>FOO</Regy>"
                + "       <Id>BAR</Id>·+"
                + "   </MktPrctc>"
                + "   <CreDt>2017-08-08T16:58:01Z</CreDt>"
                + "</AppHdr>";
        BusinessAppHdrV02 h = BusinessAppHdrV02.parse(xml);
        assertNotNull(h);
        // System.out.println(h.xml());
        assertEquals("Not available", h.getFr().getFIId().getFinInstnId().getNm());
        assertEquals("Not available", h.getTo().getFIId().getFinInstnId().getNm());
        assertEquals("AAAAAAAAAA222222", h.getBizMsgIdr());
        assertEquals("seev.037.002.02", h.getMsgDefIdr());
        assertEquals("FOO", h.getMktPrctc().getRegy());
        assertEquals("BAR", h.getMktPrctc().getId());
        assertNotNull(h.getCreDt());
    }

    @Test
    public void testParseWithPrefix() {
        final String xml = "<h:AppHdr xmlns:h=\"urn:iso:std:iso:20022:tech:xsd:head.001.001.02\">" + "   <h:Fr>"
                + "      <h:FIId>"
                + "         <h:FinInstnId>"
                + "            <h:Nm>Not available</h:Nm>"
                + "         </h:FinInstnId>"
                + "      </h:FIId>"
                + "   </h:Fr>"
                + "   <h:To>"
                + "      <h:FIId>"
                + "         <h:FinInstnId>"
                + "            <h:Nm>Not available</h:Nm>"
                + "         </h:FinInstnId>"
                + "      </h:FIId>"
                + "   </h:To>"
                + "   <h:BizMsgIdr>AAAAAAAAAA222222</h:BizMsgIdr>"
                + "   <h:MsgDefIdr>seev.037.002.02</h:MsgDefIdr>"
                + "   <h:MktPrctc>"
                + "       <h:Regy>FOO</h:Regy>"
                + "       <h:Id>BAR</h:Id>·+"
                + "   </h:MktPrctc>"
                + "   <h:CreDt>2017-08-08T16:58:01Z</h:CreDt>"
                + "</h:AppHdr>";
        BusinessAppHdrV02 h = BusinessAppHdrV02.parse(xml);
        assertNotNull(h);
        // System.out.println(h.xml());
        assertEquals("Not available", h.getFr().getFIId().getFinInstnId().getNm());
        assertEquals("Not available", h.getTo().getFIId().getFinInstnId().getNm());
        assertEquals("AAAAAAAAAA222222", h.getBizMsgIdr());
        assertEquals("seev.037.002.02", h.getMsgDefIdr());
        assertEquals("FOO", h.getMktPrctc().getRegy());
        assertEquals("BAR", h.getMktPrctc().getId());
        assertNotNull(h.getCreDt());
    }

    @Test
    public void testParseWithWrapper() {
        final String xml = "<foo><bar>" + "<AppHdr xmlns=\"urn:iso:std:iso:20022:tech:xsd:head.001.001.02\">"
                + "   <Fr>"
                + "      <FIId>"
                + "         <FinInstnId>"
                + "            <Nm>Not available</Nm>"
                + "         </FinInstnId>"
                + "      </FIId>"
                + "   </Fr>"
                + "   <To>"
                + "      <FIId>"
                + "         <FinInstnId>"
                + "            <Nm>Not available</Nm>"
                + "         </FinInstnId>"
                + "      </FIId>"
                + "   </To>"
                + "   <BizMsgIdr>AAAAAAAAAA222222</BizMsgIdr>"
                + "   <MsgDefIdr>seev.037.002.02</MsgDefIdr>"
                + "   <MktPrctc>"
                + "       <Regy>FOO</Regy>"
                + "       <Id>BAR</Id>·+"
                + "   </MktPrctc>"
                + "   <CreDt>2017-08-08T16:58:01Z</CreDt>"
                + "</AppHdr>"
                + "</bar></foo>";
        BusinessAppHdrV02 h = BusinessAppHdrV02.parse(xml);
        assertNotNull(h);
        // System.out.println(h.xml());
        assertEquals("Not available", h.getFr().getFIId().getFinInstnId().getNm());
        assertEquals("Not available", h.getTo().getFIId().getFinInstnId().getNm());
        assertEquals("AAAAAAAAAA222222", h.getBizMsgIdr());
        assertEquals("seev.037.002.02", h.getMsgDefIdr());
        assertEquals("FOO", h.getMktPrctc().getRegy());
        assertEquals("BAR", h.getMktPrctc().getId());
        assertNotNull(h.getCreDt());
    }

    @Test
    public void testParseEnvelope_PssblDplctFalse_IgnoresCpyDplct() {
        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n" + "<Envelope>\n"
                + "  <AppHdr xmlns=\"urn:iso:std:iso:20022:tech:xsd:head.001.001.02\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
                + "    <CharSet>TEXT</CharSet>\n"
                + "    <Fr>\n"
                + "      <FIId>\n"
                + "        <FinInstnId>\n"
                + "          <BICFI>BANKABCDXXX</BICFI>\n"
                + "          <ClrSysMmbId>\n"
                + "            <ClrSysId>\n"
                + "              <Cd>JONCC</Cd>\n"
                + "            </ClrSysId>\n"
                + "            <MmbId>456</MmbId>\n"
                + "          </ClrSysMmbId>\n"
                + "          <LEI>LEIABCDEFGHJIK089098</LEI>\n"
                + "        </FinInstnId>\n"
                + "      </FIId>\n"
                + "    </Fr>\n"
                + "    <To>\n"
                + "      <FIId>\n"
                + "        <FinInstnId>\n"
                + "          <BICFI>BANKDEFGXXXXXX</BICFI>\n"
                + "          <ClrSysMmbId>\n"
                + "            <ClrSysId>\n"
                + "              <Cd>JONCC</Cd>\n"
                + "            </ClrSysId>\n"
                + "            <MmbId>789</MmbId>\n"
                + "          </ClrSysMmbId>\n"
                + "          <LEI>LEIABCDEFGHJIK089123</LEI>\n"
                + "        </FinInstnId>\n"
                + "      </FIId>\n"
                + "    </To>\n"
                + "    <BizMsgIdr>TESTCNVTXXX2022</BizMsgIdr>\n"
                + "    <MsgDefIdr>pacs.009.001.08</MsgDefIdr>\n"
                + "    <BizSvc>swift.iap.tia.01</BizSvc>\n"
                + "    <MktPrctc>\n"
                + "      <Regy>MktPrctc1Regy350</Regy>\n"
                + "      <Id>MktPrctc1Id2048</Id>\n"
                + "    </MktPrctc>\n"
                + "    <CreDt>2020-03-24T10:48:00+05:30</CreDt>\n"
                + "    <CpyDplct>DUPL</CpyDplct>\n"
                + "    <PssblDplct>false</PssblDplct>\n"
                + "    <Prty>HIGH</Prty>\n"
                + "    <Rltd>\n"
                + "      <CharSet>TEXT</CharSet>\n"
                + "      <Fr>\n"
                + "        <FIId>\n"
                + "          <FinInstnId>\n"
                + "            <BICFI>BKJOJOTP252</BICFI>\n"
                + "            <ClrSysMmbId>\n"
                + "              <ClrSysId>\n"
                + "                <Cd>JONCC</Cd>\n"
                + "              </ClrSysId>\n"
                + "              <MmbId>456</MmbId>\n"
                + "            </ClrSysMmbId>\n"
                + "            <LEI>LEIABCDEFGHJIK089098</LEI>\n"
                + "          </FinInstnId>\n"
                + "        </FIId>\n"
                + "      </Fr>\n"
                + "      <To>\n"
                + "        <FIId>\n"
                + "          <FinInstnId>\n"
                + "            <BICFI>BANKABCDXXX</BICFI>\n"
                + "            <ClrSysMmbId>\n"
                + "              <ClrSysId>\n"
                + "                <Cd>JONCC</Cd>\n"
                + "              </ClrSysId>\n"
                + "              <MmbId>789</MmbId>\n"
                + "            </ClrSysMmbId>\n"
                + "            <LEI>LEIABCDEFGHJIK089123</LEI>\n"
                + "          </FinInstnId>\n"
                + "        </FIId>\n"
                + "      </To>\n"
                + "      <BizMsgIdr>JOCFTD3051831210</BizMsgIdr>\n"
                + "      <MsgDefIdr>pacs.008.001.09</MsgDefIdr>\n"
                + "      <BizSvc>swift.iap.02</BizSvc>\n"
                + "      <CreDt>2024-10-24T09:10:00+08:00</CreDt>\n"
                + "      <CpyDplct>DUPL</CpyDplct>\n"
                + "      <Prty>HIGH</Prty>\n"
                + "    </Rltd>\n"
                + "  </AppHdr>\n"
                + "  <Document xmlns=\"urn:iso:std:iso:20022:tech:xsd:pacs.009.001.08\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
                + "    <FICdtTrf>\n"
                + "      <GrpHdr>\n"
                + "        <MsgId>TESTCNVTXXX2022</MsgId>\n"
                + "        <CreDtTm>2022-05-10T10:48:00+05:30</CreDtTm>\n"
                + "        <NbOfTxs>1</NbOfTxs>\n"
                + "        <SttlmInf>\n"
                + "          <SttlmMtd>CLRG</SttlmMtd>\n"
                + "          <ClrSys>\n"
                + "            <Cd>JOD</Cd>\n"
                + "          </ClrSys>\n"
                + "        </SttlmInf>\n"
                + "      </GrpHdr>\n"
                + "      <CdtTrfTxInf>\n"
                + "        <PmtId>\n"
                + "          <InstrId>1'(RITS.)testind</InstrId>\n"
                + "          <EndToEndId>TESTCNVTXXX202204</EndToEndId>\n"
                + "          <UETR>cdd9059f-a33c-4c7a-ac0a-93f6fe3c4475</UETR>\n"
                + "        </PmtId>\n"
                + "        <PmtTpInf>\n"
                + "          <SvcLvl>\n"
                + "            <Cd>SDVA</Cd>\n"
                + "          </SvcLvl>\n"
                + "        </PmtTpInf>\n"
                + "        <IntrBkSttlmAmt Ccy=\"JOD\">0.01</IntrBkSttlmAmt>\n"
                + "        <IntrBkSttlmDt>2024-09-10</IntrBkSttlmDt>\n"
                + "        <PrvsInstgAgt1>\n"
                + "          <FinInstnId>\n"
                + "            <Nm>PRVAGT1Bethh</Nm>\n"
                + "            <PstlAdr>\n"
                + "              <TwnNm>Pasir,</TwnNm>\n"
                + "              <Ctry>JO</Ctry>\n"
                + "            </PstlAdr>\n"
                + "          </FinInstnId>\n"
                + "        </PrvsInstgAgt1>\n"
                + "        <PrvsInstgAgt1Acct>\n"
                + "          <Id>\n"
                + "            <Othr>\n"
                + "              <Id>45692462</Id>\n"
                + "              <SchmeNm>\n"
                + "                <Prtry>SchmeNmPrtry1</Prtry>\n"
                + "              </SchmeNm>\n"
                + "              <Issr>OthrIssr1</Issr>\n"
                + "            </Othr>\n"
                + "          </Id>\n"
                + "          <Tp>\n"
                + "            <Prtry>TpPrtry1</Prtry>\n"
                + "          </Tp>\n"
                + "          <Ccy>JOD</Ccy>\n"
                + "          <Nm>AcctName</Nm>\n"
                + "          <Prxy>\n"
                + "            <Tp>\n"
                + "              <Prtry>TpPrtry1</Prtry>\n"
                + "            </Tp>\n"
                + "            <Id>PrxyId1</Id>\n"
                + "          </Prxy>\n"
                + "        </PrvsInstgAgt1Acct>\n"
                + "        <PrvsInstgAgt2>\n"
                + "          <FinInstnId>\n"
                + "            <Nm>Bethh</Nm>\n"
                + "            <PstlAdr>\n"
                + "              <TwnNm>Pasir,</TwnNm>\n"
                + "              <Ctry>SG</Ctry>\n"
                + "            </PstlAdr>\n"
                + "          </FinInstnId>\n"
                + "        </PrvsInstgAgt2>\n"
                + "        <PrvsInstgAgt2Acct>\n"
                + "          <Id>\n"
                + "            <Othr>\n"
                + "              <Id>456924621</Id>\n"
                + "              <SchmeNm>\n"
                + "                <Prtry>SchmeNmPrtry2</Prtry>\n"
                + "              </SchmeNm>\n"
                + "              <Issr>OthrIssr1</Issr>\n"
                + "            </Othr>\n"
                + "          </Id>\n"
                + "          <Tp>\n"
                + "            <Prtry>TpPrtry2</Prtry>\n"
                + "          </Tp>\n"
                + "          <Ccy>JOD</Ccy>\n"
                + "          <Nm>AcctName</Nm>\n"
                + "          <Prxy>\n"
                + "            <Tp>\n"
                + "              <Prtry>TpPrtry1</Prtry>\n"
                + "            </Tp>\n"
                + "            <Id>PrxyId1</Id>\n"
                + "          </Prxy>\n"
                + "        </PrvsInstgAgt2Acct>\n"
                + "        <PrvsInstgAgt3>\n"
                + "          <FinInstnId>\n"
                + "            <Nm>Bethh</Nm>\n"
                + "            <PstlAdr>\n"
                + "              <TwnNm>PHUKET</TwnNm>\n"
                + "              <Ctry>TH</Ctry>\n"
                + "            </PstlAdr>\n"
                + "          </FinInstnId>\n"
                + "        </PrvsInstgAgt3>\n"
                + "        <PrvsInstgAgt3Acct>\n"
                + "          <Id>\n"
                + "            <Othr>\n"
                + "              <Id>456924623</Id>\n"
                + "              <SchmeNm>\n"
                + "                <Prtry>SchPrtry3</Prtry>\n"
                + "              </SchmeNm>\n"
                + "              <Issr>OthrIssr3</Issr>\n"
                + "            </Othr>\n"
                + "          </Id>\n"
                + "          <Tp>\n"
                + "            <Prtry>TpPrtry3</Prtry>\n"
                + "          </Tp>\n"
                + "          <Prxy>\n"
                + "            <Tp>\n"
                + "              <Prtry>PrxyTpPrtry</Prtry>\n"
                + "            </Tp>\n"
                + "            <Id>PrxyId</Id>\n"
                + "          </Prxy>\n"
                + "        </PrvsInstgAgt3Acct>\n"
                + "        <InstgAgt>\n"
                + "          <FinInstnId>\n"
                + "            <BICFI>BJORJOTP</BICFI>\n"
                + "            <ClrSysMmbId>\n"
                + "              <ClrSysId>\n"
                + "                <Cd>JONCC</Cd>\n"
                + "              </ClrSysId>\n"
                + "              <MmbId>565 Mmbid value</MmbId>\n"
                + "            </ClrSysMmbId>\n"
                + "            <LEI>LEIABCDEFGHJIK012301</LEI>\n"
                + "          </FinInstnId>\n"
                + "        </InstgAgt>\n"
                + "        <InstdAgt>\n"
                + "          <FinInstnId>\n"
                + "            <BICFI>CITIJO2X</BICFI>\n"
                + "            <ClrSysMmbId>\n"
                + "              <ClrSysId>\n"
                + "                <Cd>JONCC</Cd>\n"
                + "              </ClrSysId>\n"
                + "              <MmbId>4567890</MmbId>\n"
                + "            </ClrSysMmbId>\n"
                + "            <LEI>LEIABCDEFGHJIK089098</LEI>\n"
                + "          </FinInstnId>\n"
                + "        </InstdAgt>\n"
                + "        <IntrmyAgt1>\n"
                + "          <FinInstnId>\n"
                + "            <Nm>intrmyagt1MacBeth5' st(':1</Nm>\n"
                + "            <PstlAdr>\n"
                + "              <TwnNm>MUMBAI</TwnNm>\n"
                + "              <Ctry>IN</Ctry>\n"
                + "            </PstlAdr>\n"
                + "          </FinInstnId>\n"
                + "        </IntrmyAgt1>\n"
                + "        <IntrmyAgt1Acct>\n"
                + "          <Id>\n"
                + "            <Othr>\n"
                + "              <Id>234577</Id>\n"
                + "              <SchmeNm>\n"
                + "                <Prtry>SMNMPRT</Prtry>\n"
                + "              </SchmeNm>\n"
                + "              <Issr>otherissr</Issr>\n"
                + "            </Othr>\n"
                + "          </Id>\n"
                + "          <Tp>\n"
                + "            <Prtry>TPPROPXYZ</Prtry>\n"
                + "          </Tp>\n"
                + "          <Prxy>\n"
                + "            <Tp>\n"
                + "              <Prtry>PXPROPREITY</Prtry>\n"
                + "            </Tp>\n"
                + "            <Id>PRXYID</Id>\n"
                + "          </Prxy>\n"
                + "        </IntrmyAgt1Acct>\n"
                + "        <IntrmyAgt2>\n"
                + "          <FinInstnId>\n"
                + "            <Nm>MacBeth</Nm>\n"
                + "            <PstlAdr>\n"
                + "              <TwnNm>TOKYO</TwnNm>\n"
                + "              <Ctry>JP</Ctry>\n"
                + "            </PstlAdr>\n"
                + "          </FinInstnId>\n"
                + "        </IntrmyAgt2>\n"
                + "        <IntrmyAgt2Acct>\n"
                + "          <Id>\n"
                + "            <Othr>\n"
                + "              <Id>234577</Id>\n"
                + "              <SchmeNm>\n"
                + "                <Prtry>SMNMPRT</Prtry>\n"
                + "              </SchmeNm>\n"
                + "              <Issr>otherissr</Issr>\n"
                + "            </Othr>\n"
                + "          </Id>\n"
                + "          <Tp>\n"
                + "            <Prtry>TPPROPXYZ</Prtry>\n"
                + "          </Tp>\n"
                + "          <Prxy>\n"
                + "            <Tp>\n"
                + "              <Prtry>PXPROPREITY</Prtry>\n"
                + "            </Tp>\n"
                + "            <Id>PRXYID</Id>\n"
                + "          </Prxy>\n"
                + "        </IntrmyAgt2Acct>\n"
                + "        <IntrmyAgt3>\n"
                + "          <FinInstnId>\n"
                + "            <Nm>Roninintermyagt3</Nm>\n"
                + "            <PstlAdr>\n"
                + "              <TwnNm>OHUKET</TwnNm>\n"
                + "              <Ctry>ML</Ctry>\n"
                + "            </PstlAdr>\n"
                + "          </FinInstnId>\n"
                + "        </IntrmyAgt3>\n"
                + "        <IntrmyAgt3Acct>\n"
                + "          <Id>\n"
                + "            <Othr>\n"
                + "              <Id>234577</Id>\n"
                + "              <SchmeNm>\n"
                + "                <Prtry>SMNMPRT</Prtry>\n"
                + "              </SchmeNm>\n"
                + "              <Issr>otherissr</Issr>\n"
                + "            </Othr>\n"
                + "          </Id>\n"
                + "          <Tp>\n"
                + "            <Prtry>TPPROPXYZ</Prtry>\n"
                + "          </Tp>\n"
                + "          <Prxy>\n"
                + "            <Tp>\n"
                + "              <Prtry>PXPROPREITY</Prtry>\n"
                + "            </Tp>\n"
                + "            <Id>PRXYID</Id>\n"
                + "          </Prxy>\n"
                + "        </IntrmyAgt3Acct>\n"
                + "        <Dbtr>\n"
                + "          <FinInstnId>\n"
                + "            <Nm>DBTRAGTBeth5' st(':3</Nm>\n"
                + "            <PstlAdr>\n"
                + "              <TwnNm>Taiwan</TwnNm>\n"
                + "              <Ctry>JO</Ctry>\n"
                + "            </PstlAdr>\n"
                + "          </FinInstnId>\n"
                + "        </Dbtr>\n"
                + "        <DbtrAcct>\n"
                + "          <Id>\n"
                + "            <Othr>\n"
                + "              <Id>98732</Id>\n"
                + "              <SchmeNm>\n"
                + "                <Prtry>SCHNM00PRT</Prtry>\n"
                + "              </SchmeNm>\n"
                + "              <Issr>abcjklmnop</Issr>\n"
                + "            </Othr>\n"
                + "          </Id>\n"
                + "          <Tp>\n"
                + "            <Prtry>TPPRT11</Prtry>\n"
                + "          </Tp>\n"
                + "          <Prxy>\n"
                + "            <Tp>\n"
                + "              <Prtry>PXTPPRT11</Prtry>\n"
                + "            </Tp>\n"
                + "            <Id>PXID00</Id>\n"
                + "          </Prxy>\n"
                + "        </DbtrAcct>\n"
                + "        <DbtrAgt>\n"
                + "          <FinInstnId>\n"
                + "            <Nm>DBTRAGTBeth5' st(':3</Nm>\n"
                + "            <PstlAdr>\n"
                + "              <TwnNm>New York</TwnNm>\n"
                + "              <Ctry>US</Ctry>\n"
                + "            </PstlAdr>\n"
                + "          </FinInstnId>\n"
                + "        </DbtrAgt>\n"
                + "        <DbtrAgtAcct>\n"
                + "          <Id>\n"
                + "            <Othr>\n"
                + "              <Id>45619874</Id>\n"
                + "              <SchmeNm>\n"
                + "                <Prtry>SCHMENMPRTRY</Prtry>\n"
                + "              </SchmeNm>\n"
                + "              <Issr>abcdmnop</Issr>\n"
                + "            </Othr>\n"
                + "          </Id>\n"
                + "          <Tp>\n"
                + "            <Prtry>TPPRTRY</Prtry>\n"
                + "          </Tp>\n"
                + "          <Prxy>\n"
                + "            <Tp>\n"
                + "              <Prtry>PRXY000111</Prtry>\n"
                + "            </Tp>\n"
                + "            <Id>ID11</Id>\n"
                + "          </Prxy>\n"
                + "        </DbtrAgtAcct>\n"
                + "        <CdtrAgt>\n"
                + "          <FinInstnId>\n"
                + "            <Nm>Beth5' st(':1</Nm>\n"
                + "            <PstlAdr>\n"
                + "              <TwnNm>New York</TwnNm>\n"
                + "              <Ctry>JO</Ctry>\n"
                + "            </PstlAdr>\n"
                + "          </FinInstnId>\n"
                + "        </CdtrAgt>\n"
                + "        <CdtrAgtAcct>\n"
                + "          <Id>\n"
                + "            <Othr>\n"
                + "              <Id>52643</Id>\n"
                + "              <SchmeNm>\n"
                + "                <Prtry>CDTRAGTACCPRTRY</Prtry>\n"
                + "              </SchmeNm>\n"
                + "              <Issr>aeiouwxyz</Issr>\n"
                + "            </Othr>\n"
                + "          </Id>\n"
                + "          <Tp>\n"
                + "            <Prtry>CDTRAGTACCTTPPRTRY</Prtry>\n"
                + "          </Tp>\n"
                + "          <Prxy>\n"
                + "            <Tp>\n"
                + "              <Prtry>CDTRAGTACCTPXPRTRY</Prtry>\n"
                + "            </Tp>\n"
                + "            <Id>PRXYID</Id>\n"
                + "          </Prxy>\n"
                + "        </CdtrAgtAcct>\n"
                + "        <Cdtr>\n"
                + "          <FinInstnId>\n"
                + "            <ClrSysMmbId>\n"
                + "              <ClrSysId>\n"
                + "                <Cd>JONCC</Cd>\n"
                + "              </ClrSysId>\n"
                + "              <MmbId>765DFGHJKLFG</MmbId>\n"
                + "            </ClrSysMmbId>\n"
                + "            <Nm>Cdtr Name</Nm>\n"
                + "            <PstlAdr>\n"
                + "              <TwnNm>New York</TwnNm>\n"
                + "              <Ctry>JO</Ctry>\n"
                + "            </PstlAdr>\n"
                + "          </FinInstnId>\n"
                + "        </Cdtr>\n"
                + "        <CdtrAcct>\n"
                + "          <Id>\n"
                + "            <Othr>\n"
                + "              <Id>U12Y3Y89</Id>\n"
                + "              <SchmeNm>\n"
                + "                <Prtry>CDTRAGTACCTPXPRTRY</Prtry>\n"
                + "              </SchmeNm>\n"
                + "              <Issr>PRXYID</Issr>\n"
                + "            </Othr>\n"
                + "          </Id>\n"
                + "          <Tp>\n"
                + "            <Prtry>CDTRTPPRTRY</Prtry>\n"
                + "          </Tp>\n"
                + "          <Prxy>\n"
                + "            <Tp>\n"
                + "              <Prtry>PXCDTR12</Prtry>\n"
                + "            </Tp>\n"
                + "            <Id>PXID001</Id>\n"
                + "          </Prxy>\n"
                + "        </CdtrAcct>\n"
                + "        <InstrForNxtAgt>\n"
                + "          <InstrInf>/ACC/OR2N</InstrInf>\n"
                + "        </InstrForNxtAgt>\n"
                + "        <Purp>\n"
                + "          <Prtry>Prtergevev367</Prtry>\n"
                + "        </Purp>\n"
                + "      </CdtTrfTxInf>\n"
                + "    </FICdtTrf>\n"
                + "  </Document>\n"
                + "</Envelope>";

        BusinessAppHdrV02 h = BusinessAppHdrV02.parse(xml);
        assertNotNull(h);
        assertFalse(h.isPssblDplct());
    }
}
