package com.prowidesoftware.issues;

import com.prowidesoftware.swift.model.mx.AbstractMX;
import com.prowidesoftware.swift.model.mx.EnvelopeType;
import com.prowidesoftware.swift.model.mx.MxWriteConfiguration;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class Jira2895 {

    @Test
    public void test() {
        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n"
                + "<ns3:RequestPayload xmlns=\"urn:iso:std:iso:20022:tech:xsd:head.001.001.02\"\n"
                + "                    xmlns:ns2=\"urn:iso:std:iso:20022:tech:xsd:pacs.008.001.08\"\n"
                + "                    xmlns:ns3=\"urn:swift:xsd:pacs008.xxx.xx.2024\">\n"
                + "    <AppHdr>\n"
                + "        <Fr>\n"
                + "            <FIId>\n"
                + "                <FinInstnId>\n"
                + "                    <BICFI>BANKAA11XXX</BICFI>\n"
                + "                </FinInstnId>\n"
                + "            </FIId>\n"
                + "        </Fr>\n"
                + "        <To>\n"
                + "            <FIId>\n"
                + "                <FinInstnId>\n"
                + "                    <BICFI>BANKBB22XXX</BICFI>\n"
                + "                </FinInstnId>\n"
                + "            </FIId>\n"
                + "        </To>\n"
                + "        <BizMsgIdr>MSG12345ABCD0001</BizMsgIdr>\n"
                + "        <MsgDefIdr>pacs.008.001.08</MsgDefIdr>\n"
                + "        <BizSvc>swift.cbprplus.02</BizSvc>\n"
                + "        <CreDt>2025-01-15T10:30:00.123+01:00</CreDt>\n"
                + "    </AppHdr>\n"
                + "    <ns2:Document>\n"
                + "        <ns2:FIToFICstmrCdtTrf>\n"
                + "            <ns2:GrpHdr>\n"
                + "                <ns2:MsgId>MSG12345ABCD0001</ns2:MsgId>\n"
                + "                <ns2:CreDtTm>2025-01-15T10:30:00.123+01:00</ns2:CreDtTm>\n"
                + "                <ns2:NbOfTxs>1</ns2:NbOfTxs>\n"
                + "                <ns2:SttlmInf>\n"
                + "                    <ns2:SttlmMtd>INDA</ns2:SttlmMtd>\n"
                + "                </ns2:SttlmInf>\n"
                + "            </ns2:GrpHdr>\n"
                + "            <ns2:CdtTrfTxInf>\n"
                + "                <ns2:PmtId>\n"
                + "                    <ns2:InstrId>MSG12345ABCD0001</ns2:InstrId>\n"
                + "                    <ns2:EndToEndId>NOTPROVIDED</ns2:EndToEndId>\n"
                + "                    <ns2:UETR>12345678-1234-1234-1234-123456789abc</ns2:UETR>\n"
                + "                </ns2:PmtId>\n"
                + "                <ns2:PmtTpInf>\n"
                + "                    <ns2:SvcLvl>\n"
                + "                        <ns2:Cd>G001</ns2:Cd>\n"
                + "                    </ns2:SvcLvl>\n"
                + "                </ns2:PmtTpInf>\n"
                + "                <ns2:IntrBkSttlmAmt Ccy=\"EUR\">12345.67</ns2:IntrBkSttlmAmt>\n"
                + "                <ns2:IntrBkSttlmDt>2025-01-16</ns2:IntrBkSttlmDt>\n"
                + "                <ns2:InstdAmt Ccy=\"EUR\">15000.00</ns2:InstdAmt>\n"
                + "                <ns2:ChrgBr>CRED</ns2:ChrgBr>\n"
                + "                <ns2:ChrgsInf>\n"
                + "                    <ns2:Amt Ccy=\"EUR\">2654.33</ns2:Amt>\n"
                + "                    <ns2:Agt>\n"
                + "                        <ns2:FinInstnId>\n"
                + "                            <ns2:BICFI>BANKAA11XXX</ns2:BICFI>\n"
                + "                        </ns2:FinInstnId>\n"
                + "                    </ns2:Agt>\n"
                + "                </ns2:ChrgsInf>\n"
                + "                <ns2:InstgAgt>\n"
                + "                    <ns2:FinInstnId>\n"
                + "                        <ns2:BICFI>BANKAA11XXX</ns2:BICFI>\n"
                + "                    </ns2:FinInstnId>\n"
                + "                </ns2:InstgAgt>\n"
                + "                <ns2:InstdAgt>\n"
                + "                    <ns2:FinInstnId>\n"
                + "                        <ns2:BICFI>BANKBB22XXX</ns2:BICFI>\n"
                + "                    </ns2:FinInstnId>\n"
                + "                </ns2:InstdAgt>\n"
                + "                <ns2:Dbtr>\n"
                + "                    <ns2:Nm>Sample Company LLC 1234567890</ns2:Nm>\n"
                + "                    <ns2:PstlAdr>\n"
                + "                        <ns2:AdrLine>123 Main Street, Suite 100</ns2:AdrLine>\n"
                + "                        <ns2:AdrLine>City Name, Country Code</ns2:AdrLine>\n"
                + "                    </ns2:PstlAdr>\n"
                + "                </ns2:Dbtr>\n"
                + "                <ns2:DbtrAcct>\n"
                + "                    <ns2:Id>\n"
                + "                        <ns2:Othr>\n"
                + "                            <ns2:Id>12345678901234567890</ns2:Id>\n"
                + "                        </ns2:Othr>\n"
                + "                    </ns2:Id>\n"
                + "                </ns2:DbtrAcct>\n"
                + "                <ns2:DbtrAgt>\n"
                + "                    <ns2:FinInstnId>\n"
                + "                        <ns2:BICFI>BANKAA33XXX</ns2:BICFI>\n"
                + "                    </ns2:FinInstnId>\n"
                + "                </ns2:DbtrAgt>\n"
                + "                <ns2:CdtrAgt>\n"
                + "                    <ns2:FinInstnId>\n"
                + "                        <ns2:BICFI>BANKCC44XXX</ns2:BICFI>\n"
                + "                    </ns2:FinInstnId>\n"
                + "                </ns2:CdtrAgt>\n"
                + "                <ns2:Cdtr>\n"
                + "                    <ns2:Nm>BIN 9876543210 Business Corp</ns2:Nm>\n"
                + "                    <ns2:PstlAdr>\n"
                + "                        <ns2:AdrLine>456 Commerce Avenue, Building 5</ns2:AdrLine>\n"
                + "                        <ns2:AdrLine>Suite 200 City XY</ns2:AdrLine>\n"
                + "                    </ns2:PstlAdr>\n"
                + "                </ns2:Cdtr>\n"
                + "                <ns2:CdtrAcct>\n"
                + "                    <ns2:Id>\n"
                + "                        <ns2:IBAN>GB12ABCD12345678901234</ns2:IBAN>\n"
                + "                    </ns2:Id>\n"
                + "                </ns2:CdtrAcct>\n"
                + "                <ns2:InstrForCdtrAgt>\n"
                + "                    <ns2:InstrInf>/ACC/ test</ns2:InstrInf>\n"
                + "                </ns2:InstrForCdtrAgt>\n"
                + "                <ns2:RmtInf>\n"
                + "                    <ns2:Ustrd>REF1234567 Payment for services for invoice 999 dd 01.01.2025 without VAT\n"
                + "                    </ns2:Ustrd>\n"
                + "                </ns2:RmtInf>\n"
                + "            </ns2:CdtTrfTxInf>\n"
                + "        </ns2:FIToFICstmrCdtTrf>\n"
                + "    </ns2:Document>\n"
                + "</ns3:RequestPayload>";

        MxWriteConfiguration conf = new MxWriteConfiguration();
        conf.useCategoryAsDocumentPrefix = false;
        conf.envelopeType = EnvelopeType.BME_V2;
        conf.rootElement = EnvelopeType.BME_V2.rootElement();

        AbstractMX mx = AbstractMX.parse(xml);
        String resultBMEv2 = mx.message(conf);

        AbstractMX mxBMEv2 = AbstractMX.parse(resultBMEv2);

        Assertions.assertNotNull(mxBMEv2);
    }
}
